APPLICATION: demo_app1
DATA_CENTER: None
DEMO_APP.KEY: KEY
ENVIRONMENT: TEST01
GLOBALCONFIG: /home/jenkins/global-config/data/
HIERAFILE: /home/jenkins/global-config/hiera.yaml
LOG_FILE_RETENTION: '22222'
NEW_KEY: Hello world!!!
NODE: jenkins-slave-72lz1-jr0td
REGION: None
