APPLICATION: demo_app1
DATA_CENTER: None
DEMO_APP.KEY: KEY
ENVIRONMENT: TEST01
GLOBALCONFIG: /home/jenkins/global-config/data/
HIERAFILE: /home/jenkins/global-config/hiera.yaml
LOG_FILE_RETENTION: '33333'
NEW_KEY: Hello World!!!
NODE: jenkins-slave-58fzc-xs0t6
REGION: None
