APPLICATION: demo_app1
DATA_CENTER: None
DEMO_APP.KEY: KEY
ENVIRONMENT: TEST01
GLOBALCONFIG: /Users/jp0003/Documents/devops/global-config/data/
HIERAFILE: /Users/jp0003/Documents/devops/global-config/hiera.yaml
LOG_FILE_RETENTION: '22222'
NEW_KEY: Hello!!!
NODE: ml0990-0000012
REGION: None
